# -*- coding: utf-8 -*-
"""duplicates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZoKwkJ7ekUuA5_wbAICcLa-5npiHYSv
"""

## Assignment Instructions ##
## Your autotest cases will NOT work if you don’t load your sys.argv like below. For this assignment, load in your sys.argv like so:

#duplicated_words = sys.argv[1:]
#The above duplicated_words is a list-type variable which contains a whole bunch of lower-cased words (ex. ['hello', 'world', 'welcome', 'hello', 'again']).

#Create a program, duplicates.py. It should:
#Remove all duplicate words from the list
#Then print it in descending order of alphabets (from Z to A).

#Example 1 - If the list is ['apple', 'banana', 'apple', 'orange', 'pear', 'banana'], the program should print:
#['pear', 'orange', 'banana', 'apple']


# Import the sys module to use command line arguments.
import sys

# Retrieve all command line arguments after the script name and store them in the list 'duplicated_words'.
duplicated_words = sys.argv[1:]

# Convert 'duplicated_words' to a set to remove duplicates, then sort it in reverse order and store it in 'unique_words'.
unique_words = sorted(set(duplicated_words), reverse=True)

# Print the list, which contains only unique words sorted in descending order.
print(unique_words)